### ISSUE TITLE
Feature request:  Passthru exact GPS coordinates

### ISSUE THREAD

**Issue by remyderuysscher** [PimDoos/kia_connect#12]
I use the KCS from the app via the kia API.  With the request I get also GPS coordinates. 

Can you implement those coordinates rather than Away / Home but the exact GPS location? This is useful to plot the coordinates on a map with a device tracker.

Thanks.

**Comment by PimDoos** [comment]
Hey Remy, this is already implemented.
The coordinates are mapped as latitude/longitude attributes on the device_tracker entity for the vehicle.

**Comment by remyderuysscher** [comment]
> Hey Remy, this is already implemented. The coordinates are mapped as latitude/longitude attributes on the device_tracker entity for the vehicle.

Excellent! Sorry for the request will close it after testing.
