### ISSUE TITLE
Kia UVO ended

### ISSUE THREAD

**Issue by pwlivewire** [PimDoos/kia_connect#13]
They have removed Kia UVO from the UK forcing all further used through KIA Connect. Making this note the private integration! Please as other regions (UK)
![image](https://github.com/PimDoos/kia_connect/assets/25018910/0a08578e-3078-4d37-8da1-99e51e68ec2a)

**Comment by PimDoos** [comment]
This integration only supports the older implementation of MyKIA connected services as used in Dutch Kia vehicles until 2021.
For other vehicles, use the kia_uvo integration

**Comment by PimDoos** [comment]
Link: https://github.com/Hyundai-Kia-Connect/kia_uvo
