### ISSUE TITLE
not working with kia niro ev 

### ISSUE THREAD

**Issue by Alvarito2201** [PimDoos/kia_connect#15]
hello i have a question,

the integration is not working with a recent model of the kia niro ev in europe 

is this normal ??

thanks :)

**Comment by Alvarito2201** [comment]
the internet page web is 
https://www.kia.com/fr/services/kia-connect/?_tm=1706559875082

is for france 

but i dont know how to generate the json?

**Comment by PimDoos** [comment]
You are probably looking for this integration, which works with modern cars: https://github.com/Hyundai-Kia-Connect/kia_uvo

**Comment by Alvarito2201** [comment]
Already tried and not working :(

**Comment by Danny-Cap** [comment]
If you have for example a KIA e-niro before 2019, it doesn't have "Connect", but it does have "Connected Services".

Note that "Connected Services" is a very limited connectivity service, you can only read very few information (tires, range, battery, location)

While "Connect" is a full connectivity integration with WAY more options, such as remote car control via phone (heating seats, car, etc).

Make sure that you are trying to reach the right service for your car.

> hello i have a question,
> 
> the integration is not working with a recent model of the kia niro ev in europe
> 
> is this normal ??
> 
> thanks :)

**Comment by Alvarito2201** [comment]
i have a brand new niro ev 2024 version and using the cnnect app where i can turn on heater etc.. already tried both integrations in  home assistant but not working

**Comment by Alvarito2201** [comment]
Never mind , i was able to find the right integration

Kia Uvo / Hyundai Bluelink

perfectly working with my car and a ton of informations , 

thanks for all the replys we can close this
