### ISSUE TITLE
No entities for Hybrid vehicle

### ISSUE THREAD

**Issue by sonewtogithub** [PimDoos/kia_connect#17]
should this still be working. it knows what car I have,(Kia Niro hybrid 2020) and my license. But no further entities are filled

**Comment by Timple** [comment]
Works for me...

Kia e-Niro 2019

**Comment by sonewtogithub** [comment]
don't know if it matters but I am running home assistant on a virtual machine on synology nas. or is it possible it has to do anything with security settings ?

**Comment by PimDoos** [comment]
Probably due to it being a Hybrid. The onboard modem sends different data for hybrids, and I have not yet implemented this.
If you provide me with the data sent by the car, I can add this to the integration.

Can you do the following:
- Log in to https://mijnkia.nl/
- Go to 'show all vehicle information'
- Note the vehicle number at the end of the URL (`https://mijnkia.nl/mijn-auto/`**`1234567`**)
- Go to https://mijnkia.nl/api/vehicle/1234567/connected-status (replace number with vehicle number from the previous step)
- Post the output here (in a codeblock or as a file), make sure to redact your latitude/longitude for your privacy.

**Comment by PimDoos** [comment]
If done correctly, it should look something like this:

```json
{
    "data": {
        "propulsion": "BEV",
        "odoMeter": 74721,
        "range": "474",
        "doorsLocked": true,
        "handbrake": true,
        "evInfo": {
            "chargeLevel": 97,
            "isCharging": false,
            "isPlugged": false,
            "timeUntilCharged": 0,
            "averageUsage": 0
        },
        "iceInfo": null,
        "drivingStyle": {
            "eco": 92,
            "normal": 8,
            "sport": 0
        },
        "tirePressures": {
            "frontLeft": 2.8,
            "frontRight": 2.8,
            "rearLeft": 2.8,
            "rearRight": 2.8
        },
        "tireWarnings": {
            "frontLeft": false,
            "frontRight": false,
            "rearLeft": false,
            "rearRight": false
        },
        "position": {
            "latitude": REDACTED,
            "longitude": REDACTED
        }
    },
    "token": null,
    "isSuccess": true,
    "errors": []
}
```

**Comment by sonewtogithub** [comment]
Not much info. Firefox gave this info, Edge only the JSON-text
[kia output api.txt](https://github.com/PimDoos/kia_connect/files/15322860/kia.output.api.txt)

**Comment by PimDoos** [comment]
Looks like the request was not successful, can you view your vehicle data normally on mijnkia.nl?

**Comment by sonewtogithub** [comment]
there is not much info. I can see information about the fuel it uses (hybrid), the maintenance history and schedule, total km, but nothing about the entities that would be available in the integration.

**Comment by PimDoos** [comment]
Try getting the json file using de DevTools in your browser.
1. Open the devtools (F12) and go to the Network tab
1. Go to the vehicle details page on mijnkia.nl
1. Look for a request to connected-status, open it and copy the response.

**Comment by sonewtogithub** [comment]
Unfortunatelly I don't have much knowledge of the devloper tools and it's contents . I found some lines with status blocked:csp.
In the attached files all lines visible under network.
Could you please instruct how to recognize a request to connected status.

Appreciate your help 
![dev_tools_network1](https://github.com/PimDoos/kia_connect/assets/128616115/3ff1bc68-0b00-4bc2-8891-bdb4ac787434)
![dev_tools_network2](https://github.com/PimDoos/kia_connect/assets/128616115/88da1a38-d202-4ad7-be3b-b3cd755eacf1)

**Comment by PimDoos** [comment]
When I go to 'view all vehicle data' it shows it like this in the network tab. I don't see it in your screenshots, do you have an active Connected Services subscription?
![image](https://github.com/PimDoos/kia_connect/assets/17709721/6780ed53-dbdd-4ee6-ac96-a5fc8a32c2bb)

Also, some models don't work with this integration as they have a newer onboard modem. My car (e-Niro MY19) has the older 'Kia Connected Services' model, whereas newer cars use the Kia Connect app with the onboard modem formerly known as 'UVO Connect'. If your car is MY20 or higher, try the [kia_uvo](https://github.com/Hyundai-Kia-Connect/kia_uvo) integration instead.

**Comment by sonewtogithub** [comment]
The kia-uvo integration worked indeed. I Thought I needed this one because it says: "This implementation is specific to the non-UVO Kia Connected Services implementation for cars built before 2021"
I tried the UVO version but it did not work then, I don't know why. 

Thanks anyway for your help
