### ISSUE TITLE
No information at all.

### ISSUE THREAD

**Issue by TheDutchLion** [PimDoos/kia_connect#2]
Hi PimDoos.

Thanks for putting in the time for this project.
I tried to add my car with this but i can't see any data at all. Everything is "not available".
Login is accepted for mijnkia.nl.
Any tips?

Regards and again ty so far for the effort.
![Device_In_HomeAssistant](https://user-images.githubusercontent.com/105513794/168349346-ab49d2a2-920b-4eb2-8c63-ec618efb87b3.JPG)

**Comment by TheDutchLion** [comment]
Hi Pim,

Apparently Mijnkia.nl is updated to eu-account.kia.com.
Im using Kia Connected with the eu-account and not the MijnKia.nl.
What do i need to do?

**Comment by PimDoos** [comment]
Hi, you might have a different version of Connected Services. Does your car work with the UVO app? If so, you might want to check out [fuatakgun/kia_uvo](https://github.com/fuatakgun/kia_uvo).
If not, I might be able to integrate it into this component with a bit more information. I can't login to the eu-account.kia.com URL you mentioned, I get a 'not found' error. Can you see if you can spot any API calls being made using the DevTools (F12) after you log in?

**Comment by TheDutchLion** [comment]
Hi PimDoos.

Indeed kia_uvo works with my account.
Basicly what happened is my MijnKia-account was never upgraded to Kia Connect.
Instead Kia made a new account on KiaConnect. So 2 completly different accounts.

Everything sorted now.
Thanks for the reply.
You can close the issue now.
