### ISSUE TITLE
Add country Belgium

### ISSUE THREAD

**Issue by FilipNaudts** [PimDoos/kia_connect#3]
Hi, can you add https://www.kia.com/be/mykia/home/
Car model EV6

**Comment by PimDoos** [comment]
Hi Filip,

The EV6 uses Kia UVO if I'm not mistaken, which is seperate from this integration. Can you try if it works with the [fuatakgun/kia_uvo](https://github.com/fuatakgun/kia_uvo/) integration?

**Comment by FilipNaudts** [comment]
Dag Pim

‘k Neem aan dat u Nederlands verstaat 😀. Bij de integratie die u voorstelt moet je de regio USA of Canada kiezen. Jammer genoeg geen Europa of België. Is uw integratie niet om te zetten naar de Kia Belgium? Alvast bedankt. Mvgr. Filip

Verstuurd vanaf mijn iPhone

**Comment by PimDoos** [comment]
Hoi Filip, de UVO integratie zou ook Europa moeten ondersteunen, wellicht moet je account nog gemigreerd worden. Zie dit issue: https://github.com/fuatakgun/kia_uvo/issues/22

**Comment by PimDoos** [comment]
Closing this issue for now as I'm planning to merge the code for this integration into kia_uvo.
